name: Generate RSS Feeds

on:
  schedule:
    - cron: "0 */6 * * *" # Executa a cada 6 horas
  workflow_dispatch: # Permite execução manual

jobs:
  generate-feeds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 pytz feedgenerator

      - name: Run RSS generator
        run: python rss-de-valor.py

      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add -A
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update RSS feeds" && git push)
