name: RSS Scraper

on:
  schedule:
    - cron: '0 */6 * * *'  # Roda a cada 6 horas
  workflow_dispatch:  # Permite execução manual

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run scraper
      run: python main.py
        
    - name: Commit and push if changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add feeds/
        git add history/
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update feeds" && git push)