name: RSS Scraper

on:
  schedule:
    - cron: '0 */6 * * *'  # Roda a cada 6 horas
  workflow_dispatch:  # Permite execução manual

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Importante: permite que a action faça commit/push
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Importante para evitar problemas com histórico do git
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run scraper
      run: python main.py
      
    - name: Configure Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
    - name: Check for changes
      id: verify_diff
      run: |
        git add feeds/ history/
        git status
        git diff --staged --quiet && echo "no_changes=true" >> $GITHUB_OUTPUT || echo "no_changes=false" >> $GITHUB_OUTPUT
        
    - name: Commit and push if changes exist
      if: steps.verify_diff.outputs.no_changes == 'false'
      run: |
        git commit -m "Update feeds [skip ci]"
        git push